version: '3.6'
services:
  nginx:
    image: nginx:1.25.1
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - docker_network

  app:
    build: .
    env_file: configuration.env
    depends_on:
      - mongodb
      - telegraf
    ports:
      - '8080:8080'
    networks:
      - docker_network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db
    networks:
      - docker_network

  telegraf:
    image: telegraf:1.25-alpine
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    ports:
      - '127.0.0.1:8125:8125/udp'
    networks:
      - docker_network

  influxdb:
    image: influxdb:1.8-alpine
    env_file: configuration.env
    ports:
      - '127.0.0.1:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb
    networks:
      - docker_network

  grafana:
    image: grafana/grafana:8.0.2
    depends_on:
      - influxdb
    env_file: configuration.env
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    networks:
      - docker_network

volumes:
  db: {}
  grafana_data: {}
  influxdb_data: {}

networks:
  docker_network:
    driver: bridge
