server:
  port: ${SERVER_PORT}
logging:
  level:
    ROOT: INFO
    com.jdum.projector.monitoring: DEBUG
    org.springframework: INFO
    org.mongodb: ERROR
spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}
      database: ${MONGODB_NAME}
  jackson:
    default-property-inclusion: non_null
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: true
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: [ 'configprops', 'env', 'health', 'info', 'jhimetrics', 'logfile', 'loggers', 'threaddump', 'caches' ]
