server:
  port: ${SERVER_PORT}
logging:
  level:
    ROOT: INFO
    com.jdum.projector.monitoring: DEBUG
    org.springframework: INFO
    org.mongodb: ERROR
    io.micrometer: DEBUG
spring:
  data:
    elasticsearch:
      cluster-nodes: elasticsearch:9200
    mongodb:
      uri: ${MONGODB_URL}
      database: ${MONGODB_NAME}
  jackson:
    default-property-inclusion: non_null
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: true

management:
  statsd:
    metrics:
      export:
        enabled: true
        flavor: TELEGRAF
        port: 8125
        host: telegraf
        protocol: udp
  endpoints:
    web:
      base-path: /management
      exposure:
        include: [ 'configprops', 'env', 'health', 'info', 'metrics', 'logfile', 'loggers', 'threaddump', 'caches' ]
